### ISSUE TITLE
No Python 3.11 support yet

### ISSUE THREAD

**Issue by corneliusroemer** [conda-forge/yte-feedstock#18]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

yte conda-forge builds don't seem to support Python 3.11 yet

I noticed this when trying to install Snakemake=7 with Python 3.11

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

@johanneskoester

**Comment by johanneskoester** [comment]
Thanks! Just fixed by merging the migration PR.
